<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_Consolidated Statement of Investment</name>
   <tag></tag>
   <elementGuidId>44d7d00d-91ba-4e9c-a6b2-df43cbd733cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;grid&quot;)/tbody[1]/tr[@class=&quot;even&quot;][1]/td[@class=&quot;fact&quot;]/a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>id(&quot;grid&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[@class=&quot;fact&quot;]/a[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>id(&quot;grid&quot;)/tbody[1]/tr[@class=&quot;even&quot;][2]/td[@class=&quot;fact&quot;]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid&quot;)/tbody[1]/tr[@class=&quot;even&quot;][1]/td[@class=&quot;fact&quot;]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
