<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_UserLogCount</name>
   <tag></tag>
   <elementGuidId>e9c982a7-4f96-4918-859f-c9752be0b039</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;grid&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[@class=&quot;fact&quot;]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[@class=&quot;fact&quot;]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
